<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPh8MsuN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPh8MsuN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPh8MsuN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPh8MsuN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPh8MsuN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ph8MsuN',
    'container.build_id' => '465ef605',
    'container.build_time' => 1680120984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPh8MsuN');
