<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6uJRyGb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6uJRyGb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6uJRyGb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6uJRyGb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6uJRyGb\App_KernelDevDebugContainer([
    'container.build_hash' => '6uJRyGb',
    'container.build_id' => '42140f87',
    'container.build_time' => 1686513767,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6uJRyGb');
